name: taxi_app
description: A Flutter Taxi App Project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.1.0  # برای گرفتن موقعیت کاربر
  # فایربیس
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  # نقشه Map.ir (اگر SDK رسمی نداشت، از flutter_map استفاده می‌کنیم ولی با تایل‌های Map.ir)
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  http: ^1.1.0 # برای درخواست‌های API
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
